# Generated by Django 4.1.1 on 2022-10-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='age',
            new_name='sex',
        ),
    ]
